### ISSUE TITLE
feat: Add new icons 

### ISSUE THREAD

**Issue by ManonPolle** [Decathlon/vitamin-web#1317]
**To do**

Add new icons (8)

- [ ] [tablet-line & tablet-fill](https://github.com/Decathlon/vitamin-design/issues/119)
![tablet](https://user-images.githubusercontent.com/46710837/208639631-13a84d06-64d0-46b9-82be-d200e7cfae72.png)
<img width="323" alt="image" src="https://user-images.githubusercontent.com/46710837/208700194-0ef09c48-87ec-47e2-873d-505d5a9cb38f.png">

- [ ] [run-line & run-fill](https://github.com/Decathlon/vitamin-design/issues/123)
<img width="325" alt="image" src="https://user-images.githubusercontent.com/46710837/208700243-21fa5f0d-82f6-4d4f-b216-848f76ff9c59.png">

- [ ] [sparkles-line & sparkles-fill](https://github.com/Decathlon/vitamin-design/issues/134)
<img width="328" alt="image" src="https://user-images.githubusercontent.com/46710837/208700313-0d05508f-915f-4cff-8e19-10decb67214d.png">

- [ ] [logout-box-line & logout-box-fill](https://github.com/Decathlon/vitamin-design/issues/137)
<img width="324" alt="image" src="https://user-images.githubusercontent.com/46710837/208700089-36532e07-f65e-4758-ba6c-2c0a0c539fc5.png">
