### ISSUE TITLE
feat(@vtmn/icons): add new icons

### ISSUE THREAD

**Issue by ManonPolle** [Decathlon/vitamin-web#1337]
**To do**

Add new icons (8)

- [ ] [shopping-bag-line & shopping-bag-fill](https://github.com/Decathlon/vitamin-design/issues/145)
<img width="228" alt="image" src="https://user-images.githubusercontent.com/46710837/213412546-2304dbfc-0d2c-4e20-b108-9fbf164cc93b.png">

- [ ] [seed-1-line & seed-1-fill](https://github.com/Decathlon/vitamin-design/issues/139)
<img width="193" alt="image" src="https://user-images.githubusercontent.com/46710837/213412648-0aa05551-b87c-4d55-87b1-fcf56754cc36.png">

- [ ] [seed-2-line & seed-2-fill](https://github.com/Decathlon/vitamin-design/issues/140)
<img width="194" alt="image" src="https://user-images.githubusercontent.com/46710837/213412711-4806af7e-fe99-4dca-b80a-b391da34cf9d.png">

- [ ] [seed-3-line & seed-3-fill](https://github.com/Decathlon/vitamin-design/issues/141)
<img width="209" alt="image" src="https://user-images.githubusercontent.com/46710837/213412754-06da7a8e-56e1-4080-9a99-222407025ef3.png">
